# Generated by Django 5.2.6 on 2025-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjournal', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F')], default='F', max_length=3),
            preserve_default=False,
        ),
    ]
