# Generated by Django 5.2.6 on 2025-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjournal', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=15000),
        ),
    ]
